# -------------------------------------------------------------------------------- load data
setwd(paste(project_folder, "Source data - not tracked", sep = ""))

folder.contents <- data.frame(list.files(path = getwd()))

folder.contents <- list.files(path = getwd())
for (i in 1:length(folder.contents)) assign(folder.contents[i], 
	read.csv(folder.contents[i], header = FALSE, stringsAsFactors = FALSE, fileEncoding = "latin1", strip.white = TRUE))

# clean up environment
rm(folder.contents, i)

# these source tables are generated by:
# opening the source tab in COR 
# transpose/paste-as-values into a new sheet
# the source data only labels every 4th or 5th row with the service area. so manually build a new column in the csv with the blanks filled in
# pru 1819 estimate has separate cols for the name of the variable and the point in time. so i concatenated these in the csv
# no other changes

# -------------------------------------------------------------------------------- label columns
colnames(financing_pru_0304.csv) <- financing_pru_0304.csv[2,]
colnames(financing_pru_0405.csv) <- financing_pru_0405.csv[2,]
colnames(financing_pru_0506.csv) <- financing_pru_0506.csv[2,]
colnames(financing_pru_0607.csv) <- financing_pru_0708.csv[2,]
colnames(financing_pru_0708.csv) <- financing_pru_0708.csv[2,]
colnames(financing_pru_0809.csv) <- financing_pru_0809.csv[2,]
colnames(financing_pru_0910.csv) <- financing_pru_0910.csv[2,]
colnames(financing_pru_1011.csv) <- financing_pru_1011.csv[2,]
colnames(financing_pru_1112.csv) <- financing_pru_1112.csv[2,]
colnames(financing_pru_1213.csv) <- financing_pru_1213.csv[2,]
colnames(financing_pru_1314.csv) <- financing_pru_1314.csv[2,]
colnames(financing_pru_1415.csv) <- financing_pru_1415.csv[2,]
colnames(financing_pru_1516.csv) <- financing_pru_1516.csv[3,]
colnames(financing_pru_1617.csv) <- financing_pru_1617.csv[3,]

colnames(financing_1718.csv) <- financing_1718.csv[3,]
colnames(pru_1718.csv) <- pru_1718.csv[3,]

colnames(financing_1819.csv) <- financing_1819.csv[3,]
colnames(CFR_1819.csv) <- CFR_1819.csv[3,]
colnames(pru_1819.csv) <- pru_1819.csv[3,]

colnames(financing_1718_estimate.csv) <- financing_1718_estimate.csv[2,]
colnames(pru_1718_estimate.csv) <- pru_1718_estimate.csv[2,]

colnames(financing_1819_estimate.csv) <- financing_1819_estimate.csv[3,]
colnames(pru_1819_estimate.csv) <- pru_1819_estimate.csv[3,]

colnames(financing_1920_estimate.csv) <- financing_1920_estimate.csv[3,]
colnames(pru_1920_estimate.csv) <- pru_1920_estimate.csv[3,]

# -------------------------------------------------------------------------------- drop unwanted rows from the top of each table
financing_pru_0304.csv <- financing_pru_0304.csv[-c(1:4),]
financing_pru_0405.csv <- financing_pru_0405.csv[-c(1:4),]
financing_pru_0506.csv <- financing_pru_0506.csv[-c(1:4),]
financing_pru_0607.csv <- financing_pru_0607.csv[-c(1:4),]
financing_pru_0708.csv <- financing_pru_0708.csv[-c(1:4),]
financing_pru_0809.csv <- financing_pru_0809.csv[-c(1:4),]
financing_pru_0910.csv <- financing_pru_0910.csv[-c(1:4),]
financing_pru_1011.csv <- financing_pru_1011.csv[-c(1:4),]
financing_pru_1112.csv <- financing_pru_1112.csv[-c(1:4),]
financing_pru_1213.csv <- financing_pru_1213.csv[-c(1:3),]
financing_pru_1314.csv <- financing_pru_1314.csv[-c(1:3),]
financing_pru_1415.csv <- financing_pru_1415.csv[-c(1:3),]
financing_pru_1516.csv <- financing_pru_1516.csv[-c(1:4),]
financing_pru_1617.csv <- financing_pru_1617.csv[-c(1:4),]

financing_1718.csv <- financing_1718.csv[-c(1:5),]
pru_1718.csv <- pru_1718.csv[-c(1:5),]

financing_1819.csv <- financing_1819.csv[-c(1:5),]
CFR_1819.csv <- CFR_1819.csv[-c(1:5),]
pru_1819.csv <- pru_1819.csv[-c(1:5),]

financing_1718_estimate.csv <- financing_1718_estimate.csv[-c(1:4),]
pru_1718_estimate.csv <- pru_1718_estimate.csv[-c(1:4),]

financing_1819_estimate.csv <- financing_1819_estimate.csv[-c(1:6),]
pru_1819_estimate.csv <- pru_1819_estimate.csv[-c(1:6),]

financing_1920_estimate.csv <- financing_1920_estimate.csv[-c(1:5),]
pru_1920_estimate.csv <- pru_1920_estimate.csv[-c(1:5),]

# -------------------------------------------------------------------------------- manually identify the columns with variable names
colnames(financing_pru_0304.csv)[2] <- "original_variable"
colnames(financing_pru_0405.csv)[3] <- "original_variable"
colnames(financing_pru_0506.csv)[3] <- "original_variable"
colnames(financing_pru_0607.csv)[3] <- "original_variable"
colnames(financing_pru_0708.csv)[2] <- "original_variable"
colnames(financing_pru_0809.csv)[2] <- "original_variable"
colnames(financing_pru_0910.csv)[3] <- "original_variable"
colnames(financing_pru_1011.csv)[2] <- "original_variable"
colnames(financing_pru_1112.csv)[1] <- "original_variable"
colnames(financing_pru_1213.csv)[2] <- "original_variable"
colnames(financing_pru_1314.csv)[1] <- "original_variable"
colnames(financing_pru_1415.csv)[1] <- "original_variable"
colnames(financing_pru_1516.csv)[1] <- "original_variable"
colnames(financing_pru_1617.csv)[7] <- "original_variable"

colnames(financing_1718.csv)[4] <- "original_variable"
colnames(pru_1718.csv)[1] <- "original_variable"

colnames(financing_1819.csv)[5] <- "original_variable"
colnames(CFR_1819.csv)[5] <- "original_variable"
colnames(pru_1819.csv)[5] <- "original_variable"

colnames(financing_1718_estimate.csv)[2] <- "original_variable"
colnames(pru_1718_estimate.csv)[1] <- "original_variable"

colnames(financing_1819_estimate.csv)[4] <- "original_variable"
colnames(pru_1819_estimate.csv)[1] <- "original_variable"

colnames(financing_1920_estimate.csv)[2] <- "original_variable"
colnames(pru_1920_estimate.csv)[2] <- "original_variable"


# by now every column we want to keep is labelled. drop columns that are not labelled. 
# clean_names() converts blanks to 'x', NA to 'na', everything else to lower case with underscore instead of space
# select(-c()) only works if every item in the list exists in the data
financing_pru_0304.csv %<>% clean_names() %>% select(-c(x, na))
financing_pru_0405.csv %<>% clean_names() %>% select(-c(x, na, na_2))
financing_pru_0506.csv %<>% clean_names() %>% select(-c(x, na))
financing_pru_0607.csv %<>% clean_names() %>% select(-c(x, x_2, na))
financing_pru_0708.csv %<>% clean_names() %>% select(-c(x, na, na_2))
financing_pru_0809.csv %<>% clean_names() %>% select(-c(x, na, na_2))
financing_pru_0910.csv %<>% clean_names() %>% select(-c(x, na, na_2))
financing_pru_1011.csv %<>% clean_names() %>% select(-c(x, na))
financing_pru_1112.csv %<>% clean_names() %>% select(-c(na))
financing_pru_1213.csv %<>% clean_names() %>% select(-c(x, x_2, x_3, x_4, na, na_2))
financing_pru_1314.csv %<>% clean_names() %>% select(-c(na, na_2))
financing_pru_1415.csv %<>% clean_names() %>% select(-c(na, la_name))
financing_pru_1516.csv %<>% clean_names() %>% select(-c(na))
financing_pru_1617.csv %<>% clean_names() %>% select(-c(x, x_2, x_3, x_4, x_5, na, na_2))

financing_1718.csv %<>% 	clean_names() %>% select(-c(x, x_2, x_3, na, national_totals, la_name))
pru_1718.csv %<>% 			clean_names() %>% select(-c(na, national_totals))

financing_1819.csv %<>% 	clean_names() %>% select(-c(x, x_2, x_3, na, national_totals, la_name))
CFR_1819.csv %<>%			clean_names() %>% select(-c(x, x_2, x_3, na, national_totals, la_name))
pru_1819.csv %<>%			clean_names() %>% select(-c(x, x_2, x_3, na, national_totals, la_name))

financing_1718_estimate.csv %<>% clean_names() %>% select(-c(x, na))
pru_1718_estimate.csv %<>% 	clean_names() %>% select(-c(x, na, na_2))

financing_1819_estimate.csv %<>% clean_names() %>% select(-c(x, x_2, x_3, na))
pru_1819_estimate.csv %<>% 	clean_names() %>% select(-c(x, x_2, na, la_name))

financing_1920_estimate.csv %<>% clean_names() %>% select(-c(x, na, national_totals))
pru_1920_estimate.csv %<>% 	clean_names() %>% select(-c(x, na, national_totals))


# gather and stack
financing_pru_0304.csv <- gather(financing_pru_0304.csv, LA, value, 2:ncol(financing_pru_0304.csv))
financing_pru_0405.csv <- gather(financing_pru_0405.csv, LA, value, 2:ncol(financing_pru_0405.csv))
financing_pru_0506.csv <- gather(financing_pru_0506.csv, LA, value, 2:ncol(financing_pru_0506.csv))
financing_pru_0607.csv <- gather(financing_pru_0607.csv, LA, value, 2:ncol(financing_pru_0607.csv))
financing_pru_0708.csv <- gather(financing_pru_0708.csv, LA, value, 2:ncol(financing_pru_0708.csv))
financing_pru_0809.csv <- gather(financing_pru_0809.csv, LA, value, 2:ncol(financing_pru_0809.csv))
financing_pru_0910.csv <- gather(financing_pru_0910.csv, LA, value, 2:ncol(financing_pru_0910.csv))
financing_pru_1011.csv <- gather(financing_pru_1011.csv, LA, value, 2:ncol(financing_pru_1011.csv))
financing_pru_1112.csv <- gather(financing_pru_1112.csv, LA, value, 2:ncol(financing_pru_1112.csv))
financing_pru_1213.csv <- gather(financing_pru_1213.csv, LA, value, 2:ncol(financing_pru_1213.csv))
financing_pru_1314.csv <- gather(financing_pru_1314.csv, LA, value, 2:ncol(financing_pru_1314.csv))
financing_pru_1415.csv <- gather(financing_pru_1415.csv, LA, value, 2:ncol(financing_pru_1415.csv))
financing_pru_1516.csv <- gather(financing_pru_1516.csv, LA, value, 2:ncol(financing_pru_1516.csv))
financing_pru_1617.csv <- gather(financing_pru_1617.csv, LA, value, 2:ncol(financing_pru_1617.csv))

financing_pru_1718.csv <- bind_rows(
	gather(financing_1718.csv, LA, value, 2:ncol(financing_1718.csv)), 
	gather(pru_1718.csv, LA, value, 2:ncol(pru_1718.csv)))

financing_pru_1819.csv <- bind_rows(
	gather(financing_1819.csv, LA, value, 2:ncol(financing_1819.csv)),
	gather(CFR_1819.csv, LA, value, 2:ncol(CFR_1819.csv)), 
	gather(pru_1819.csv, LA, value, 2:ncol(pru_1819.csv)))

financing_pru_1718_estimate.csv <- bind_rows(
	gather(financing_1718_estimate.csv, LA, value, 2:ncol(financing_1718_estimate.csv)), 
	gather(pru_1718_estimate.csv, LA, value, 2:ncol(pru_1718_estimate.csv)))

financing_pru_1819_estimate.csv <- bind_rows(
	gather(financing_1819_estimate.csv, LA, value, 2:ncol(financing_1819_estimate.csv)), 
	gather(pru_1819_estimate.csv, LA, value, 2:ncol(pru_1819_estimate.csv)))

financing_pru_1920_estimate.csv <- bind_rows(
	gather(financing_1920_estimate.csv, LA, value, 2:ncol(financing_1920_estimate.csv)), 
	gather(pru_1920_estimate.csv, LA, value, 2:ncol(pru_1920_estimate.csv)))

rm(	financing_1718.csv, pru_1718.csv, 
	financing_1819.csv, pru_1819.csv, CFR_1819.csv,
	financing_1718_estimate.csv, pru_1718_estimate.csv, 
	financing_1819_estimate.csv, pru_1819_estimate.csv, 
	financing_1920_estimate.csv, pru_1920_estimate.csv)


# date and stack
financing_pru_0304.csv$Year <- "2003-04"
financing_pru_0405.csv$Year <- "2004-05"
financing_pru_0506.csv$Year <- "2005-06"
financing_pru_0607.csv$Year <- "2006-07"
financing_pru_0708.csv$Year <- "2007-08"
financing_pru_0809.csv$Year <- "2008-09"
financing_pru_0910.csv$Year <- "2009-10"
financing_pru_1011.csv$Year <- "2010-11"
financing_pru_1112.csv$Year <- "2011-12"
financing_pru_1213.csv$Year <- "2012-13"
financing_pru_1314.csv$Year <- "2013-14"
financing_pru_1415.csv$Year <- "2014-15"
financing_pru_1516.csv$Year <- "2015-16"
financing_pru_1617.csv$Year <- "2016-17"
financing_pru_1718.csv$Year <- "2017-18"
financing_pru_1819.csv$Year <- "2018-19"

financing_pru_1718_estimate.csv$Year <- "2017-18e"
financing_pru_1819_estimate.csv$Year <- "2018-19e"
financing_pru_1920_estimate.csv$Year <- "2019-20e"

financing_pru <- bind_rows(
	financing_pru_0304.csv, financing_pru_0405.csv, financing_pru_0506.csv, financing_pru_0607.csv,
	financing_pru_0708.csv, financing_pru_0809.csv, financing_pru_0910.csv,
	financing_pru_1011.csv, financing_pru_1112.csv, financing_pru_1213.csv, financing_pru_1314.csv,
	financing_pru_1415.csv, financing_pru_1516.csv, financing_pru_1617.csv, financing_pru_1718.csv, 
	financing_pru_1819.csv,
	financing_pru_1718_estimate.csv, financing_pru_1819_estimate.csv, financing_pru_1920_estimate.csv)

financing_pru$Units <- "GPBmillions"
financing_pru$value <- round(as.numeric(financing_pru$value)/1000,3)


rm(	financing_pru_0304.csv, financing_pru_0405.csv, financing_pru_0506.csv, financing_pru_0607.csv,
	financing_pru_0708.csv, financing_pru_0809.csv, financing_pru_0910.csv,
	financing_pru_1011.csv, financing_pru_1112.csv, financing_pru_1213.csv, financing_pru_1314.csv,
	financing_pru_1415.csv, financing_pru_1516.csv, financing_pru_1617.csv, financing_pru_1718.csv,
	financing_pru_1819.csv,
	financing_pru_1718_estimate.csv, financing_pru_1819_estimate.csv, financing_pru_1920_estimate.csv)


# check unwanted cols (eg blanks, NAs) were all dropped
col_check <- data.frame(table(financing_pru$LA))

# write out
setwd(paste(project_folder, "Intermediate outputs", sep = ""))

# convert to a wide CSV (which takes less space than long)
financing_pru <- financing_pru %>% spread(Year, value)

ifelse(write_out_y_n == "y", write.csv(financing_pru, file = "01 Capital outturn financing and pru_stack.csv", row.names = FALSE), "")

rm(col_check)